#pragma once

#include <algorithm>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <vector>

#include "minimax_regression.hpp"
#include "merge_sorted.hpp"
#include "dup_optimal.hpp"

namespace maximize_maxerror {

// Generate "consecutive" poisons to the RIGHT of anchor index i:
// start = keys[i] + 1, then take the next `lambda` missing integers,
// skipping over existing keys.
inline std::vector<uint64_t> make_consec_right(const std::vector<uint64_t>& keys,
                                                size_t i,
                                                size_t lambda) {
    std::vector<uint64_t> poisons;
    poisons.reserve(lambda);
    if (lambda == 0) return poisons;

    const size_t n = keys.size();
    uint64_t cur = keys[i];

    // handle overflow on +1 safely
    if (cur == std::numeric_limits<uint64_t>::max()) return {}; // no room to add to the right
    uint64_t now = cur + 1;

    size_t j = i; // we may advance j while skipping keys[j+1]
    while (poisons.size() < lambda) {
        // skip if we hit next legitimate key
        if (j + 1 < n && now == keys[j + 1]) {
            ++j;
            if (now == std::numeric_limits<uint64_t>::max()) break;
            ++now;
            continue;
        }
        poisons.push_back(now);
        if (now == std::numeric_limits<uint64_t>::max()) break;
        ++now;
    }
    if (poisons.size() != lambda) return {}; // not enough representable values
    return poisons; // already sorted increasing
}

// Generate "consecutive" poisons to the LEFT of anchor index i:
// start = keys[i] - 1, then take the next `lambda` missing integers,
// skipping over existing keys.
inline std::vector<uint64_t> make_consec_left(const std::vector<uint64_t>& keys,
                                               size_t i,
                                               size_t lambda) {
    std::vector<uint64_t> poisons;
    poisons.reserve(lambda);
    if (lambda == 0) return poisons;

    if (keys[i] == 0) return {}; // no room to add to the left
    uint64_t now = keys[i] - 1;

    size_t j = i; // we may move j left while skipping keys[j-1]
    while (poisons.size() < lambda) {
        if (j >= 1 && now == keys[j - 1]) {
            --j;
            if (now == 0) break;
            --now;
            continue;
        }
        poisons.push_back(now);
        if (now == 0) break;
        --now;
    }
    if (poisons.size() != lambda) return {};
    std::reverse(poisons.begin(), poisons.end()); // make increasing
    return poisons;
}

// Brute-force over all "consecutive (skip-legit)" poison sequences:
// - choose an anchor key i
// - try RIGHT and LEFT
// - compute max_error via minimax_maxabs_regression_rank(sorted_poisoned_keys)
// - keep the poisons that maximize max_error
//
// keys must be strictly increasing (sorted unique).
// If allow_duplicates is true, delegate to dup_optimal.
inline void consec(const std::vector<uint64_t>& keys,
                  std::vector<uint64_t>& poisons,
                  size_t lambda,
                  bool allow_duplicates = false) {
    poisons.clear();
    if (keys.empty()) throw std::runtime_error("keys must be non-empty");
    if (lambda == 0) return;

    if (allow_duplicates) {
        dup_optimal(keys, poisons, lambda);
        return;
    }

    // sanity check: strictly increasing
    for (size_t k = 1; k < keys.size(); ++k) {
        if (!(keys[k - 1] < keys[k])) {
            throw std::runtime_error("keys must be strictly increasing (sorted unique)");
        }
    }

    double best = -std::numeric_limits<double>::infinity();
    std::vector<uint64_t> best_p;

    auto eval_candidate = [&](const std::vector<uint64_t>& cand_poisons) {
        if (cand_poisons.size() != lambda) return;

        // cand_poisons should be sorted; also should not overlap with keys if generated by our routines
        auto poisoned_keys = merge_sorted(keys, cand_poisons);

        // minimax_maxabs_regression_rank requires sorted input; merge_sorted preserves sort.
        auto [slope, intercept, max_error] = minimax_maxabs_regression_rank(poisoned_keys);
        (void)slope; (void)intercept;

        if (max_error > best) {
            best = max_error;
            best_p = cand_poisons;
        }
    };

    const size_t n = keys.size();
    for (size_t i = 0; i < n; ++i) {
        auto pR = make_consec_right(keys, i, lambda);
        auto [pR_min, pR_max] = std::minmax_element(pR.begin(), pR.end());
        if (!pR.empty() && keys[0] < *pR_min && *pR_max < keys[n - 1]) eval_candidate(pR);

        auto pL = make_consec_left(keys, i, lambda);
        auto [pL_min, pL_max] = std::minmax_element(pL.begin(), pL.end());
        if (!pL.empty() && keys[0] < *pL_min && *pL_max < keys[n - 1]) eval_candidate(pL);
    }

    // // If nothing worked (e.g., extreme under/overflow), keep empty and signal.
    // if (best_p.empty()) {
    //     throw std::runtime_error("No feasible consecutive poison sequence found (likely due to uint64 range limits)");
    // }

    poisons = std::move(best_p);
}

}  // namespace maximize_maxerror
